[package]
name = "bcg_backup"
version = "0.1.0"
edition = "2021"

[dependencies]
registry = "1.2.3"
thiserror = "1.0"
dirs = "5.0"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
chrono = "0.4"
ratatui = "0.28.1"
sysinfo = "0.32.0"
